--- #YAML:1.0
name: Text-WikiFormat
version: 0.6
license: perl
distribution_type: module
requires:
  Test::More: 0.3
  URI::Escape: ''
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
