---
abstract: 'module for translating Wiki formatted text into other formats'
author:
  - 'chromatic, C<chromatic@wgz.org>, with much input from the Jellybean team'
build_requires:
  Test::More: 0.30
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-WikiFormat
provides:
  Text::WikiFormat:
    file: lib/Text/WikiFormat.pm
    version: 0.81
  Text::WikiFormat::Block:
    file: lib/Text/WikiFormat/Blocks.pm
    version: 0
  Text::WikiFormat::Block::code:
    file: lib/Text/WikiFormat/Blocks.pm
    version: 0
  Text::WikiFormat::Blocks:
    file: lib/Text/WikiFormat/Blocks.pm
    version: 0
requires:
  Scalar::Util: 1.14
  URI::Escape: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.81
